### ISSUE TITLE
Unexpected behaviour with virtual spaces in InfiniteMPS constructor

### ISSUE THREAD

**Issue by Gertian** [QuantumKitHub/MPSKit.jl#162]
Hi, 

I was using the  InfiniteMPS constructor but got some errors down the line. 
https://github.com/QuantumKitHub/MPSKit.jl/blob/b35df94938fda0d7f6376c25e49a4932d74a2b9e/src/states/infinitemps.jl#L121

After some playing I suspect that this constructor should have : circshift(Dspaces, -1) rather then circshift(Dspaces, 1). At least this solved the issue for me. 

In case it's not entirely clear I can give some more context off course :)

**Comment by lkdvos** [comment]
Honestly, this is definitely possible. I never really looked into these things in detail, it would be great to get this sorted out and add some tests. See also #103

**Comment by Gertian** [comment]
Ok, I'll write a super simple test for this today :)

**Comment by lkdvos** [comment]
Just double checking, what is the unexpected behaviour? According to the current definitions, the `Dspaces[i]` should be the virtual space to the right of the `i`th site, is this not what is happening?
```julia
julia> using MPSKit

julia> psi = InfiniteMPS([2,2,2,2], [4,5,6,7])
4-site InfiniteMPS:
│   ⋮
│ CR[4]: TensorMap(ℂ^7 ← ℂ^7)
├── AL[4]: TensorMap((ℂ^6 ⊗ ℂ^2) ← ℂ^7)
├── AL[3]: TensorMap((ℂ^5 ⊗ ℂ^2) ← ℂ^6)
├── AL[2]: TensorMap((ℂ^4 ⊗ ℂ^2) ← ℂ^5)
├── AL[1]: TensorMap((ℂ^7 ⊗ ℂ^2) ← ℂ^4)
│   ⋮
```
This looks correct to me?

**Comment by Gertian** [comment]
You are right !
But like you mentioned in the above post it's a bit unnatural to expect Dspaces[i] to be the virtual space to the right of site i. 
This caused my confusion. Thanks for figuring this out !

**Comment by lkdvos** [comment]
Just for completeness, the reason this is the case is that for FiniteMPS, this really is the most natural index convention, as you don't typically expect a virtual space to the left of the first site. In that sense, while we do explicitly add one there, you can think about them as being labeled by `0:N` instead of `1:(N+1)`. While I do think we should make this all more obvious in the docs, I don't think there is a good enough reason to change this.

**Comment by Gertian** [comment]
That's a very good point actually, it will help me not forget this again thanks !
