### ISSUE TITLE
Possible bug for the multiplication between a `FiniteMPO` and `FiniteMPS`

### ISSUE THREAD

**Issue by waltergu** [QuantumKitHub/MPSKit.jl#183]
https://github.com/QuantumKitHub/MPSKit.jl/blob/cd0372630c023f0c2708c27b882af67d89ff4a3e/src/operators/densempo.jl#L235-L236

It seems that `right_virtualspace(A[i])` and `right_virtualspace(mpo, i)` should be corrected to `right_virtualspace(A[i])'` and `right_virtualspace(mpo, i)'`, becase apparently, `fuse(right_virtualspace(A[i]), right_virtualspace(mpo, i))` is not isomorphic to `right_virtualspace(A[i])' * right_virtualspace(mpo, i)'`

**Comment by lkdvos** [comment]
Good catch, thank you!
